name: Tests

on:
  push:
    branches:
      - master

jobs:
  go_test:
    strategy:
      matrix:
        go: ['1.18']
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Configure tools
        run: |
          go get -u -v github.com/jandelgado/gcov2lcov
      - name: Install dependencies
        run: |
          go version
          go get -v
      - name: Run unit tests and generate coverage info
        run: |
          go test -v -race -cover -coverprofile=coverage.out ./...
          mkdir coverage
          gcov2lcov -infile=coverage.out -outfile=./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
