name: Tests

on:
  push:
    branches:
      - master

jobs:
  go_test:
    strategy:
      matrix:
        go: ['1.18']
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go version
          go get -v
      - name: Run unit tests and generate coverage info
        run: |
          go test -v -race -cover -coverprofile=coverage.out ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
